
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - prometheus
    volumes:
      - /etc/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - '9100:9100'
    networks:
      - prometheus

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    hostname: pushgateway
    restart: always
    ports:
      - '9091:9091'
    networks:
      - prometheus

networks:
  prometheus:

